language: generic
sudo: required
dist: trusty
services:
  - docker
matrix:
  include:
    - env: ARCH=x86_64 ARCH_CMD=linux64
      os: linux
    - os: osx
before_install: bin/ci prepare_system
install: bin/ci prepare_build
script:
  - bin/ci with_build_env 'make'
branches:
  only:
    - master
after_success: 
  - make build-release
  - chmod +x ./biplane 
  - zip biplane-linux-x86_64.zip ./biplane
deploy:
  skip_cleanup: true
